////
This document is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
[id="reference-doc-quarkus-documentation"]
= Quarkus documentation reference

include::attributes.adoc[]

Abstract. A short introduction that describes the content of this reference. This summary should help a reader determine if this document is likely to contain the information they are looking for.

////
If this is a reference for an experimental or tech-preview extension, uncomment the following (otherwise delete)
include::{includes}/extension-status.adoc[]
////

== Additional sections

- xref:doc-create-reference-tutorial.adoc[Tutorial: Create a Reference document]
- xref:doc-concept.adoc[Documentation concepts]
- xref:doc-reference.adoc[Quarkus documentation reference]

Notes from https://diataxis.fr/reference/:

- Be consistent
- Be accurate
- Do nothing but describe (link to tutorials, how-to guides, or concepts/explainers as necessary)
- Include examples where appropriate, e.g. an example usage of a command

Language tips:

- State facts about how things work: X is an example of y.
- List commands, options, operations, features, flags, limitations, error messages, etc.
- Provide warnings where appropriate

////
== Configuration Reference

include::{generated-dir}/config/<<generated-filename>>.adoc[opts=optional, leveloffset=+1]
////