////
This document is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
////
TODO: Title should have an implied "How to.." in front. See
////
[id="howto-..."]
= Title in sentence case
////
TODO: If this is a reference for an experimental or tech-preview extension, uncomment the following and set the appropriate status (otherwise delete)
:extension-status: preview
////
include::attributes.adoc[]

Abstract. How-to guides are goal-oriented, and should help the reader accomplish a task (where there may be forks in the path).

////
TODO: If this is a reference for an experimental or tech-preview extension, uncomment the following (otherwise delete)
include::{includes}/extension-status.adoc[]
////

== Define the problem

Your user will also be in the middle of something: define the starting-point that they know how to reach and a conclusion that answers a real question.

== Resources

- xref:{docref}/doc-create-howto-tutorial.adoc[Tutorial: Create a How-To]
- xref:{docref}/doc-concept.adoc[Documentation concepts]
- xref:{docref}/doc-reference.adoc[Quarkus documentation reference]

== Guidelines for good How-To guides

- Don’t explain concepts; link to a related concept/explainer
- Be flexible; a how-to guide needs to be adaptable to real-world use-cases.
- Omit the unnecessary; practical usability is more helpful than completeness.

== Examples

Baeldung tutorials provide solid examples of How-To guides. For example, "How to use Jackson annotations" is answered (with variations) here: https://www.baeldung.com/jackson-annotations